# Generated by Django 6.1 on 2026-08-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="difficulty",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
